EmployeeSignInSystem/Employee.SignIn.System/Controllers/EmployeeController.cs
using EmployeeSignInSystem.Models;
using EmployeeSignInSystem.Services;
using Microsoft.AspNetCore.Mvc;
using System.Windows;
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Xceed.Wpf.Toolkit;
using Microsoft.AspNetCore.Http;
using EmployeeSignInSystem.Models;

namespace EmployeeSignIn.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        public EmployeeController(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

             
        [HttpGet]
        public IActionResult SignIn(string FirstName = "", string LastName = "")
        {
            ViewBag.FirstName = FirstName;
            ViewBag.LastName = LastName;
            
            ViewBag.RequestStatus = TempData["RequestStatus"];
            ViewBag.SignOutEmp = TempData["SignOutEmp"];
            IEnumerable<EmployeeDetails> empRecords = _employeeService.GetEmployeesByName(FirstName, LastName);
            return View(empRecords);
        }
        [HttpGet]
        public IActionResult GetBadgeQueue(string Id, EmployeeSignInSystem.Models.EmployeeTempBadge temp)
        {

            //Saving sign In Time for the selected employee
            var a=_employeeService.SaveSignInTime(Id, temp);
            
            if (a != 0)
            {
                TempData["RequestStatus"] = "Your Request for Temporary Badge has been sent";
                return RedirectToAction("SignIn");
            }
            TempData["RequestStatus"] = "You have already sent your Request for Temporary Badge today. It's in queue";
            return RedirectToAction("SignIn");
            

        }
        
        public IActionResult SignOut(string FirstName="",string LastName="")
        {
            ViewBag.FirstName = FirstName;
            ViewBag.LastName = LastName;
            IEnumerable<EmpQueueDetails> emps = _employeeService.GetEmpsToSignOut(FirstName, LastName);


            return View(emps);
        }

        [HttpGet]
        public IActionResult SignEmpOut(string EmployeeId)
        {
            //Saving sign In Time for the selected employee
            var a = _employeeService.SaveSignOutTime(EmployeeId);

            if (a != 0)
            {
                TempData["SignOutEmp"] = "Successfully signed out";
                return RedirectToAction("SignIn");
            }
            TempData["SignOutEmp"] = "Error occurred";
            return RedirectToAction("SignIn");
        }
    }
}

EmployeeSignInSystem/Employee.SignIn.System/Controllers/GuardController.cs
using Azure.Messaging;
using EmployeeSignInSystem.Models;
using EmployeeSignInSystem.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using Xceed.Wpf.Toolkit;

namespace EmployeeSignInSystem.Controllers
{
    public class GuardController : Controller
    {
        private readonly IGuardService _guardService;
        public GuardController(IGuardService guardService)
        {
            _guardService = guardService;
        }      

        public IActionResult GetBadgeQueue()
        {
            ViewBag.TempBadgeStatus = TempData["TempBadgeStatus"];
            //Fetching employees who are in queue to receive badges
            IEnumerable<EmpQueueDetails> inQueueEmps = _guardService.BadgeQueueEmps();
            return View(inQueueEmps);
        }
        public IActionResult AssignBadge(string TempBadge,string id)
        {
            var saved=_guardService.SaveAssignTime(TempBadge,id);
            if (saved == 1)
            {
                
                TempData["TempBadgeStatus"] = "Temporary Badge is assigned";
                return RedirectToAction("GetBadgeQueue");
            }
            TempData["TempBadgeStatus"] = "This Temporary badge number has already been assigned to other employee";
            return RedirectToAction("GetBadgeQueue");
        }

        public IActionResult GetAssignedBadges() 
        {
            IEnumerable<EmpQueueDetails> empsWithTempBadges=_guardService.BadgeOutEmps();
            return View(empsWithTempBadges);
        
        }

        public IActionResult GetReport(DateTime StartDate, DateTime EndDate , string FirstName = "", string LastName = "")
        {
            ViewBag.FirstName=FirstName; ViewBag.LastName=LastName;
            ViewBag.StartDate=StartDate; ViewBag.EndDate=EndDate;
            if(EndDate == DateTime.MinValue)
            {
                EndDate = DateTime.MaxValue;
            }
            IEnumerable<EmployeeTempBadge> emps = _guardService.GetReport(StartDate, EndDate , FirstName, LastName);

            return View(emps);

        }
       
    }
}

EmployeeSignInSystem/Employee.SignIn.System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeSignIn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="SignIn"><b>Employee Signing System</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="SignIn"><b>Employee_SignIn</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="SignOut"><b>Employee_SignOut</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Guard_Login</b></a>
                        </li>

                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeeSignIn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EmployeeSignInSystem/Employee.SignIn.System/Views/Shared/_LayoutEmployee.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeSignIn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="Main"><b>Employee Signing System</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="SignIn"><b>SignIn</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="SignOut"> <b>SignOut</b></a>
                        </li>

                      
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeeSignIn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

EmployeeSignInSystem/Employee.SignIn.System/Views/Shared/_LayoutGuard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeSignIn</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="SignIn"><b>Employee Signing System</b></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-3">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item ">
                                <i class="fa-solid fa-user"></i>
                                <a class="nav-link text-dark" style="color:orangered;">@User.Identity?.Name</a>
                            </li>

                            <li class="nav-item ">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        </ul>
                        <ul class="navbar-nav flex-grow-1">
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (ViewBag.CurrentUrl == "~/Guard/GetBadgeQueue")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" style="background-color:mediumseagreen; text-decoration:underline"  asp-area="" asp-controller="Guard" asp-action="GetBadgeQueue">Badge Queue</a>
                                </li>

                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Guard" asp-action="GetBadgeQueue"><b>Badge Queue</b></a>
                                </li>
                            }

                            @if (ViewBag.CurrentUrl == "~/Guard/GetAssignedBadges")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" style="background-color:mediumseagreen; text-decoration:underline" asp-area="" asp-controller="Guard" asp-action="GetAssignedBadges"><b>Badge Out</b></a>
                                    </li>
                                
                            }
                            else{
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Guard" asp-action="GetAssignedBadges"><b>Badge Out</b></a>
                                    </li>
                            }
                            @if (ViewBag.CurrentUrl == "~/Guard/GetReport")
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" style="background-color:mediumseagreen; text-decoration:underline" asp-area="" asp-controller="Guard" asp-action="GetReport"><b>Report</b></a>
                                </li>

                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Guard" asp-action="GetReport"><b>Report</b></a>
                                    </li>
                            }
                        }
                        else
                        {                                                                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login"><b>Guard Login</b></a>
                             </li>                                                               
                        }
                    </ul>
                   
                       
                </div>
              
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - EmployeeSignIn - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>